package carrent;
// Generated Apr 30, 2018 8:01:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Lob;
import org.hibernate.annotations.Type;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private int reg;
     private String model;
     private String type;
     private int rent;
     private String availability;
     @Lob
@Type(type="org.hibernate.type.PrimitiveByteArrayBlobType")
byte[] myBlob;
     private byte[] image;
     private Set bookings = new HashSet(0);

    public Cars() {
    }

	
    public Cars(int reg, String model, String type, int rent, String availability) {
        this.reg = reg;
        this.model = model;
        this.type = type;
        this.rent = rent;
        this.availability = availability;
    }
    public Cars(int reg, String model, String type, int rent, String availability, byte[] image, Set bookings) {
       this.reg = reg;
       this.model = model;
       this.type = type;
       this.rent = rent;
       this.availability = availability;
       this.image = image;
       this.bookings = bookings;
    }
   
    public int getReg() {
        return this.reg;
    }
    
    public void setReg(int reg) {
        this.reg = reg;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getRent() {
        return this.rent;
    }
    
    public void setRent(int rent) {
        this.rent = rent;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


