package CarRent;
// Generated Apr 11, 2018 8:18:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private Integer id;
     private Cars cars;
     private Customer customer;
     private Date bookingDate;
     private Date pickDate;
     private Date dropDate;

    public Booking() {
    }

    public Booking(Cars cars, Customer customer, Date bookingDate, Date pickDate, Date dropDate) {
       this.cars = cars;
       this.customer = customer;
       this.bookingDate = bookingDate;
       this.pickDate = pickDate;
       this.dropDate = dropDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cars getCars() {
        return this.cars;
    }
    
    public void setCars(Cars cars) {
        this.cars = cars;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public Date getPickDate() {
        return this.pickDate;
    }
    
    public void setPickDate(Date pickDate) {
        this.pickDate = pickDate;
    }
    public Date getDropDate() {
        return this.dropDate;
    }
    
    public void setDropDate(Date dropDate) {
        this.dropDate = dropDate;
    }




}


