package CarRent;
// Generated Apr 11, 2018 8:18:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private int reg;
     private String model;
     private String type;
     private int rent;
     private String availability;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Cars() {
    }

	
    public Cars(int reg, String model, String type, int rent, String availability) {
        this.reg = reg;
        this.model = model;
        this.type = type;
        this.rent = rent;
        this.availability = availability;
    }
    public Cars(int reg, String model, String type, int rent, String availability, Set<Booking> bookings) {
       this.reg = reg;
       this.model = model;
       this.type = type;
       this.rent = rent;
       this.availability = availability;
       this.bookings = bookings;
    }
   
    public int getReg() {
        return this.reg;
    }
    
    public void setReg(int reg) {
        this.reg = reg;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getRent() {
        return this.rent;
    }
    
    public void setRent(int rent) {
        this.rent = rent;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


