package CarRent;
// Generated Apr 11, 2018 8:18:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private int contact;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Customer() {
    }

	
    public Customer(String name, String address, int contact) {
        this.name = name;
        this.address = address;
        this.contact = contact;
    }
    public Customer(String name, String address, int contact, Set<Booking> bookings) {
       this.name = name;
       this.address = address;
       this.contact = contact;
       this.bookings = bookings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getContact() {
        return this.contact;
    }
    
    public void setContact(int contact) {
        this.contact = contact;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


